version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  scraper:
    build: .
    restart: always
    command: "/bin/sh -c 'while true; do bash ./script; sleep 24h; done'"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
    depends_on:
      - mongo
      - mongo-express
volumes:
  mongodata:
